"""empty message

Revision ID: 9a32b2d19042
Revises: f7b19ac8ef74
Create Date: 2021-04-28 10:43:09.125673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a32b2d19042'
down_revision = 'f7b19ac8ef74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mail', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mail')
    # ### end Alembic commands ###
