"""empty message

Revision ID: 7000a0640f6d
Revises: c1d86a25cf15
Create Date: 2021-04-29 09:49:37.174893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7000a0640f6d'
down_revision = 'c1d86a25cf15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mail', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'mail')
    # ### end Alembic commands ###
